### ISSUE TITLE
这个包依赖太大了. 目前用在实际项目中使用吗

### ISSUE THREAD

**Issue by alberthuang24** [zedisdog/laravel-yz-sdk#1]

**Comment by zedisdog** [comment]
已经在实际项目中使用了。这个肯定要依赖laravel，然后`xu42/open-sdk`这个是有赞官网上面提到的sdk，主要就是对这个包进行包装，然后`orchestra/testbench`这个做测试用的，我之后要把这个移到`require-dev`去。

**Comment by HongjiangHuang** [comment]
不是说包的依赖. 是实现上- -. 譬如 不应该直接 依赖 request...

**Comment by HongjiangHuang** [comment]
https://github.com/zedisdog/laravel-yz-sdk/blob/master/src/Http/HookController.php#L20

https://github.com/zedisdog/laravel-yz-sdk/blob/master/src/YzOpenSdk.php#L94

**Comment by zedisdog** [comment]
我明白你的意思了 我也觉得这个很怪

**Comment by zedisdog** [comment]
之前是想在掉用的时候少写参数 哈哈哈哈 下次改过来

**Comment by zedisdog** [comment]
@HongjiangHuang 我在考虑移除 `request` 依赖，但是感觉没办法移除啊。没有 `request` 就不知道url上面有没有code。有没有好的建议啊？

**Comment by HongjiangHuang** [comment]
我的项目里面有例子。我等等贴出来

**Comment by HongjiangHuang** [comment]
可以看看，easywechat. 内部依赖一个实现了 psr 规范的 cache 来缓存code就可以了。用起来很方便。一般的项目都会有实现了psr cache规范的组件。就算没有。自己实现一个也很简单。

**Comment by zedisdog** [comment]
好
